Feature/add sfdx scanner (#56)
* added ruleset, changed ci-pr

* updates to ruleset

* updates to ci-pr

* changes to ci-pr

* added threshold to ci-pr

* added new rules

* fixed PMD code errors

* updates to ruleset

* added uat/main target to package

* fixed log errors

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -52,7 +52,7 @@ jobs:
               if: ${{ contains(github.event.client_payload.packageNames, 'CoreApp') }}
               run: |
                   set +e
-                  json=$(sfdx force:package:version:create -p CoreApp -x -w 20 --json)
+                  json=$(sfdx force:package:version:create -p CoreApp -x -w 20 --json --codecoverage)
                   echo $json
                   status=$(echo $json | jq '.status')
                   if [ $status == "0" ]; then
@@ -69,7 +69,7 @@ jobs:
               if: ${{ contains(github.event.client_payload.packageNames, 'PortfolioApp') }}
               run: |
                   set +e
-                  json=$(sfdx force:package:version:create -p PortfolioApp -x -w 20 --json)
+                  json=$(sfdx force:package:version:create -p PortfolioApp -x -w 20 --json --codecoverage)
                   echo $json
                   status=$(echo $json | jq '.status')
                   if [ $status == "0" ]; then
@@ -86,7 +86,7 @@ jobs:
               if: ${{ contains(github.event.client_payload.packageNames, 'MortgageApp') }}
               run: |
                   set +e
-                  json=$(sfdx force:package:version:create -p MortgageApp -x -w 20 --json)
+                  json=$(sfdx force:package:version:create -p MortgageApp -x -w 20 --json --codecoverage)
                   echo $json
                   status=$(echo $json | jq '.status')
                   if [ $status == "0" ]; then
@@ -107,9 +107,27 @@ jobs:
             - name: 'Update sfdx-project.json and README'
               uses: trailheadapps/github-action-sfdx-packaging-updater@1.1.0
 
-            # Create scratch org
-            - name: 'Create scratch org'
-              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+            # Store secret for environment
+            - name: 'Populate auth file with SFDX_URL secret'
+              shell: bash
+              run: |
+                  if [${{ github.event.client_payload.branch }} == 'uat']; then
+                    echo ${{ secrets.UAT_SFDX_URL}} > ./SFDX_URL.txt
+                  else if [${{ github.event.client_payload.branch }} == 'main']; then
+                    echo ${{ secrets.MAIN_SFDX_URL}} > ./SFDX_URL.txt
+                  secretFileSize=$(wc -c "./SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+
+            # Authenticate environment
+            - name: 'Authenticate environment'
+              run: sfdx auth:sfdxurl:store -f ./SFDX_URL.txt -a ${{ github.event.client_payload.branch }} -d
+
+            # Remove auth file
+            - name: 'Remove auth file'
+              run: rm -f ./SFDX_URL.txt
 
             # Get package version IDs
             - name: 'Get package version IDs'
@@ -123,19 +141,19 @@ jobs:
             - name: 'Install into scratch org - Core App'
               run: |
                   versionId=$(echo '${{ steps.packageVersions.outputs.ids }}' | jq -r '.CoreApp')
-                  sfdx force:package:install --package $versionId -w 10 -u scratch-org -r
+                  sfdx force:package:install --package $versionId -w 10 -u ${{ github.event.client_payload.branch }} -r
 
             # Install into scratch org - Portfolio App
             - name: 'Install into scratch org - Portfolio App'
               run: |
                   versionId=$(echo '${{ steps.packageVersions.outputs.ids }}' | jq -r '.PortfolioApp')
-                  sfdx force:package:install --package $versionId -w 10 -u scratch-org -r
+                  sfdx force:package:install --package $versionId -w 10 -u ${{ github.event.client_payload.branch }} -r
 
             # Install into scratch org - Mortgage App
             - name: 'Install into scratch org - Mortgage App'
               run: |
                   versionId=$(echo '${{ steps.packageVersions.outputs.ids }}' | jq -r '.MortgageApp')
-                  sfdx force:package:install --package $versionId -w 10 -u scratch-org -r
+                  sfdx force:package:install --package $versionId -w 10 -u ${{ github.event.client_payload.branch }} -r
 
             # The main branch is protected, so we have to take a sequea for updating the README through a new PR
             - name: 'Create PR for new package versions'
